import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import { brisa } from "./fonts";
import "./globals.css";
import Header from "@/app/components/landing/Header";
import Footer from "@/app/components/landing/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${brisa.variable} ${jost.variable} antialiased`}
      >
                <Header />
        {children}
              <Footer />
      </body>
    </html>
  );
}